export const PLACES = [
  "Paris, France",
  "Rome, Italy",
  "New York City, United States",
  "London, United Kingdom",
  "Tokyo, Japan",
  "Barcelona, Spain",
  "Sydney, Australia",
  "Berlin, Germany",
  "Amsterdam, Netherlands",
  "San Francisco, United States",
  "Dubai, United Arab Emirates",
  "Mumbai, India",
  "Cape Town, South Africa",
  "Rio de Janeiro, Brazil",
  "Moscow, Russia",
  "Toronto, Canada",
  "Buenos Aires, Argentina",
  "Hong Kong, China",
  "Istanbul, Turkey",
  "Seoul, South Korea",
  "Cairo, Egypt",
  "Vienna, Austria",
  "Stockholm, Sweden",
  "Athens, Greece",
  "Prague, Czech Republic",
  "Havana, Cuba",
  "Bangkok, Thailand",
  "Lisbon, Portugal",
  "Copenhagen, Denmark",
  "Oslo, Norway",
  "Edinburgh, United Kingdom",
  "Zurich, Switzerland",
  "Helsinki, Finland",
  "Brussels, Belgium",
  "Mexico City, Mexico",
  "Warsaw, Poland",
  "Budapest, Hungary",
  "Dublin, Ireland",
  "Jerusalem, Israel",
  "Singapore, Singapore",
  "Reykjavik, Iceland",
  "Wellington, New Zealand",
  "Nairobi, Kenya",
  "São Paulo, Brazil",
  "Bogota, Colombia",
  "Beirut, Lebanon",
  "Amman, Jordan",
  "Seville, Spain",
  "Marrakech, Morocco",
  "Florence, Italy",
  "Krakow, Poland",
  "Santorini, Greece",
  "Phuket, Thailand",
  "Machu Picchu, Peru",
  "Hawaii, United States",
  "Cancun, Mexico",
  "Venice, Italy",
  "Cusco, Peru",
  "Granada, Spain",
  "Dubrovnik, Croatia",
  "Galapagos Islands, Ecuador",
  "Petra, Jordan",
  "Iguazu Falls, Argentina/Brazil",
  "Yellowstone National Park, United States",
  "Great Barrier Reef, Australia",
  "Taj Mahal, India",
  "Serengeti National Park, Tanzania",
  "Meteora, Greece",
  "Bora Bora, French Polynesia",
  "Chichen Itza, Mexico",
  "Angkor Wat, Cambodia",
  "Salar de Uyuni, Bolivia",
  "The Pyramids of Giza, Egypt",
  "The Great Wall of China, China",
  "The Colosseum, Italy",
  "The Acropolis, Greece",
  "The Louvre, France",
  "The Alhambra, Spain",
  "The Sagrada Familia, Spain",
  "The Grand Canyon, United States",
  "The Eiffel Tower, France",
  "The Statue of Liberty, United States",
  "The Sydney Opera House, Australia",
  "The Taj Mahal, India",
  "The Great Sphinx, Egypt",
  "The Kremlin, Russia",
  "The Parthenon, Greece",
  "The Palace Museum (Forbidden City), China",
  "The Buckingham Palace, United Kingdom",
  "The St. Peter's Basilica, Vatican City",
  "The Mount Everest, Nepal/China",
  "The Mount Kilimanjaro, Tanzania",
  "The Niagara Falls, United States/Canada",
  "The Amazon Rainforest, Various Countries",
  "The Serengeti National Park, Tanzania",
  "The Northern Lights, Various Countries",
  "The Victoria Falls, Zambia/Zimbabwe",
  "The Santorini, Greece",
  "The Maldives, Maldives",
  "The Easter Island, Chile",
  "The Machu Picchu, Peru",
  "The Plitvice Lakes National Park, Croatia",
  "The Antelope Canyon, United States",
  "The Moai Statues, Easter Island",
  "The Neuschwanstein Castle, Germany",
  "The Yosemite National Park, United States",
  "The Blue Lagoon, Iceland",
  "The Mount Fuji, Japan",
  "The Table Mountain, South Africa",
  "The Great Barrier Reef, Australia",
  "The Angel Falls, Venezuela",
  "The Mount Rushmore, United States",
  "The Ayers Rock (Uluru), Australia",
  "The Zhangjiajie National Forest Park, China",
  "The Red Square, Russia",
  "The Valley of the Kings, Egypt",
  "The Christ the Redeemer, Brazil",
  "The Borobudur Temple, Indonesia",
  "The Dead Sea, Jordan/Israel/Palestine",
  "The Potala Palace, China",
  "The Stonehenge, United Kingdom",
  "The Iguazu Falls, Argentina/Brazil",
  "The Dubai Burj Khalifa, United Arab Emirates",
  "The Sahara Desert, Various Countries",
  "The Piazza San Marco, Italy",
  "The Bagan Temples, Myanmar",
  "The Palace of Versailles, France",
  "The Westminster Abbey, United Kingdom",
  "The Golden Gate Bridge, United States",
  "The Mecca, Saudi Arabia",
  "The Mont Saint-Michel, France",
  "The Ngorongoro Crater, Tanzania",
  "The Hagia Sophia, Turkey",
  "The Valley of Fire State Park, United States",
  "The Giant's Causeway, United Kingdom",
  "The Bryce Canyon National Park, United States",
  "The St. Basil's Cathedral, Russia",
  "The Alcatraz Island, United States",
  "The Auschwitz-Birkenau Memorial and Museum, Poland",
  "The Blue Mosque, Turkey",
  "The St. Mark's Basilica, Italy",
  "The Acropolis Museum, Greece",
  "The Rijksmuseum, Netherlands",
  "The MoMA (Museum of Modern Art), United States",
  "The British Museum, United Kingdom",
  "The Prado Museum, Spain",
  "The Louvre Museum, France",
  "The Uffizi Gallery, Italy",
  "The Metropolitan Museum of Art, United States",
  "The Hermitage Museum, Russia",
  "The National Gallery, United Kingdom",
  "The Van Gogh Museum, Netherlands",
  "The Tate Modern, United Kingdom",
  "The Guggenheim Museum Bilbao, Spain",
  "The Museum of Fine Arts, United States",
  "The Museum of Contemporary Art, Japan",
  "The National Museum of China, China",
  "The National Palace Museum, Taiwan",
  "The Vatican Museums, Vatican City",
  "The Natural History Museum, United Kingdom",
  "The Smithsonian Institution, United States",
  "The Cairo Citadel, Egypt",
  "The Golden Temple, India",
  "The Brandenburg Gate, Germany",
  "The Santorini Caldera, Greece",
  "The Cape of Good Hope, South Africa",
  "The Horseshoe Bend, United States",
  "The Valley of the Moon, Chile",
  "The Grand Palace, Thailand",
  "The Lake Bled, Slovenia",
  "The Park Guell, Spain",
  "The Blue Mountains, Australia",
  "The Capilano Suspension Bridge, Canada",
  "The Tivoli Gardens, Denmark",
  "The Trevi Fountain, Italy",
  "The Blue Grotto, Italy",
  "The Arashiyama Bamboo Grove, Japan",
  "The Nijo Castle, Japan",
  "The Giza Plateau, Egypt",
  "The Rocky Mountains, United States/Canada",
  "The Redwood National and State Parks, United States",
  "The Valley of Desolation, South Africa",
  "The Plaka, Greece",
  "The Forbidden City, China",
  "The Times Square, United States",
  "The Fisherman's Bastion, Hungary",
  "The Palace of Fine Arts, United States",
  "The Cliffs of Moher, Ireland",
  "The Tower Bridge, United Kingdom",
  "The Petra Treasury, Jordan",
  "The Pyramids of Teotihuacan, Mexico",
  "The Pena Palace, Portugal",
  "The Masai Mara National Reserve, Kenya",
  "The Nara Park, Japan",
  "The Sistine Chapel, Vatican City",
  "The Garden of the Gods, United States",
  "The Lake Louise, Canada",
  "The Royal Palace of Madrid, Spain",
  "The Yosemite Falls, United States",
  "The Palawan Island, Philippines",
  "The Jeju Island, South Korea",
  "The Galapagos Islands, Ecuador",
  "The Meteora Monasteries, Greece",
  "The Ulun Danu Beratan Temple, Indonesia",
  "The Angkor Wat, Cambodia",
];
